"""Email delivery via Resend."""

from __future__ import annotations

import os
from typing import Any

import resend


class DeliveryError(Exception):
    """Raised when delivery to a channel fails."""


def send_report_email(
    to_email: str,
    repo_name: str,
    report_summary: str | None,
    risk_score: float | None,
    report_url: str,
) -> str:
    """Send a health report email via Resend.

    Returns the Resend email ID on success.
    Raises DeliveryError on failure.
    """
    api_key = os.environ.get("RESEND_API_KEY")
    if not api_key:
        msg = "RESEND_API_KEY environment variable is not set"
        raise DeliveryError(msg)

    from_email = os.environ.get("RESEND_FROM_EMAIL", "reports@autopsy.dev")

    html = _build_email_html(repo_name, report_summary, risk_score, report_url)

    try:
        resend.api_key = api_key
        result: Any = resend.Emails.send({
            "from": from_email,
            "to": [to_email],
            "subject": f"Autopsy Health Report: {repo_name}",
            "html": html,
        })
        return str(result.get("id", "")) if isinstance(result, dict) else str(result)
    except Exception as e:
        msg = f"Failed to send email via Resend: {e}"
        raise DeliveryError(msg) from e


def _build_email_html(
    repo_name: str,
    summary: str | None,
    risk_score: float | None,
    report_url: str,
) -> str:
    """Build HTML email content."""
    summary_html = f"<p>{summary}</p>" if summary else "<p>Report generated successfully.</p>"

    return f"""
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                max-width: 600px; margin: 0 auto; padding: 20px;">
        <h1 style="color: #1f2937; margin-bottom: 4px;">Autopsy</h1>
        <h2 style="color: #6b7280; font-weight: normal; margin-top: 0;">
            Health Report: {repo_name}
        </h2>
        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;" />
        {summary_html}
        <div style="text-align: center; margin: 30px 0;">
            <a href="{report_url}"
               style="background-color: #2563eb; color: white; padding: 12px 24px;
                      border-radius: 6px; text-decoration: none; font-weight: 600;">
                View Full Report
            </a>
        </div>
        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;" />
        <p style="color: #9ca3af; font-size: 12px;">
            This report was generated by Autopsy. Manage your delivery preferences in settings.
        </p>
    </div>
    """
